
repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks: [ { id: black } ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.3.3
    hooks: [ { id: prettier } ]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks: [ { id: markdownlint, args: ["--disable","MD013"] } ]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks: [ { id: yamllint } ]
